import { NextResponse } from 'next/server';
import { pedidoSchema } from '@/lib/validations';
import { createClient } from '@/lib/supabase/server';
import { resend, FROM_EMAIL, ADMIN_EMAIL, generateOrderConfirmationHTML, generateAdminNotificationHTML } from '@/lib/resend';

export async function POST(request: Request) {
  try {
    const body = await request.json();

    // 1. Validate the request body with Zod
    const validation = pedidoSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: 'Datos de pedido inválidos', details: validation.error.format() },
        { status: 400 }
      );
    }

    const {
      cliente_nombre,
      cliente_email,
      cliente_whatsapp,
      cliente_direccion,
      cliente_ciudad,
      producto_id,
      talla,
      cantidad,
      notas,
    } = validation.data;

    const supabase = await createClient();

    // A. Fetch product to get snapshot of name & price
    const { data: product, error: productError } = await supabase
      .from('productos')
      .select('nombre, precio')
      .eq('id', producto_id)
      .single();

    if (productError || !product) {
      return NextResponse.json({ error: 'Producto no encontrado' }, { status: 404 });
    }

    const total = Number(product.precio) * cantidad;

    // B. Insert order (numero_pedido generated by database trigger)
    const { data: newOrder, error: orderError } = await supabase
      .from('pedidos')
      .insert({
        cliente_nombre,
        cliente_email,
        cliente_whatsapp,
        cliente_direccion,
        cliente_ciudad,
        producto_id,
        producto_nombre: product.nombre,
        producto_precio: product.precio,
        talla,
        cantidad,
        notas,
        estado: 'pendiente',
        total
      })
      .select('id, numero_pedido')
      .single();

    if (orderError || !newOrder) {
      console.error('Error inserting order in Supabase:', orderError);
      return NextResponse.json({ error: 'Error al registrar pedido' }, { status: 500 });
    }

    // C. Insert status history log
    const { error: historyError } = await supabase.from('pedido_historial').insert({
      pedido_id: newOrder.id,
      estado: 'pendiente',
      nota: 'Pedido recibido por la tienda.'
    });

    if (historyError) {
      console.error('Error inserting order history log in Supabase:', historyError);
    }

    // D. Send email confirmation to client
    try {
      if (process.env.RESEND_API_KEY && process.env.RESEND_API_KEY !== 're_xxx') {
        await resend.emails.send({
          from: FROM_EMAIL,
          to: cliente_email,
          subject: `Tu pedido ${newOrder.numero_pedido} fue recibido 🔥`,
          html: generateOrderConfirmationHTML({
            numero_pedido: newOrder.numero_pedido,
            cliente_nombre,
            producto_nombre: product.nombre,
            talla,
            cantidad,
            total,
            pedido_id: newOrder.id,
          }),
        });

        // E. Send email notification to admin
        await resend.emails.send({
          from: FROM_EMAIL,
          to: ADMIN_EMAIL,
          subject: `🔔 Nuevo Pedido: ${newOrder.numero_pedido}`,
          html: generateAdminNotificationHTML({
            numero_pedido: newOrder.numero_pedido,
            cliente_nombre,
            producto_nombre: product.nombre,
            talla,
            cantidad,
            total,
            pedido_id: newOrder.id,
          }),
        });
      } else {
        console.log('Skipping email send because RESEND_API_KEY is placeholder or not configured.');
      }
    } catch (emailErr) {
      console.error('Error sending Resend emails:', emailErr);
      // We don't fail the request if emails fail, but we log it
    }

    return NextResponse.json({
      success: true,
      pedido_id: newOrder.id,
      numero_pedido: newOrder.numero_pedido
    });
  } catch (err) {
    console.error('Error in pedidos API:', err);
    return NextResponse.json(
      { error: 'Error interno del servidor' },
      { status: 500 }
    );
  }
}
